import java.util.Properties;

import org.apache.kafka.clients.producer.Callback;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.clients.producer.RecordMetadata;
import org.apache.kafka.common.serialization.StringSerializer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Producer {

    public static void main(String[] args) {
        Logger logger = LoggerFactory.getLogger(Producer.class);

        // Crear las propiedades del producer
        Properties properties = new Properties();
        properties.setProperty(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");

        properties.setProperty(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());

        properties.setProperty(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());

        // Crearemos el producer

        KafkaProducer<String, String> kafkaProducer = new KafkaProducer<String, String>(properties);

        // Enviaremos los datos

        for (int i = 0; i < 10; i++) {
            // Crear los datos
            ProducerRecord<String, String> producerRecord = 
                new ProducerRecord<String, String>("primer-topic",
                "miapp",
                    "mensaje vespertino "+i);

            // Enviarlos
            kafkaProducer.send(producerRecord, new Callback() {
                @Override
                public void onCompletion(RecordMetadata metadata, Exception exception) {
                    // Se ejecuta cuando se ha terminado de enviar
                    // o bien ha habido un error en el envío
                    if (exception == null) {
                        // todo ha ido bien
                        logger.info("mensaje enviado");
                        logger.info("topic " + metadata.topic());
                        logger.info("offset " + metadata.offset());
                        logger.info("particion "+metadata.partition());
                    } else {
                        // no ha ido bien
                        logger.error(exception.getLocalizedMessage(), exception);
                    }

                }
            });
        }
        kafkaProducer.flush();

        // Cerrar
        kafkaProducer.close();

    }
}
